### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by rantler** [socrata/oauth_sample_app_ruby#2]
It hasn't effectively been changed in 7 years. If it's dead, the repo should be removed.

**Comment by issa-tseng** [comment]
that's perhaps a philosophical question. is a code sample ever dead?

relevantly, it is still linked here: https://dev.socrata.com/docs/authentication.html
and al boss used it ~4 years ago in creating his own stuff.

**Comment by issa-tseng** [comment]
on the other hand, i strongly suspect that floating the gem versions has completely broken the code, so it probably needs code changes to stay relevant.

**Comment by rantler** [comment]
Thanks a bunch for the response! I agree that floating the gem versions probably isn't the best idea. The goal was to update the older gems for several CVEs that github flagged. It was particularly difficult to selectively update some of the gems because they were so old.

For now, I'll add a disclaimer to the repo indicating that it is currently untested and potential users should either file issues, or reach out to us if they intend to use the sample code and are having difficulty.

**Comment by rantler** [comment]
Closing this issue since we now know that this repo, while severely out-of-date, is not in fact dead.
